spring.datasource.url=jdbc:mysql://localhost:3306/worker_spot
spring.datasource.username=root
spring.datasource.password=Asif@MySQL#2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

jwt.secret=WorkerSpotDevelopmentSecretKey2026VeryLongRandomValue123456789

msg91.authkey=561254AZ1GDCyb7Kh6a81f047P1
msg91.verify-url=https://control.msg91.com/api/v5/widget/verifyAccessToken
razorpay.key.id=rzp_test_T9Ub23vOjXebYi
razorpay.key.secret=MseJumpdEIPdyxJfrqN1N0UG